### PR TITLE
DT-835: Removed internal application from architecture diagram

### PR DESCRIPTION
**Pull request by keithkennedy**

### CODE REVIEW

**Comment by BenRamchandani** [comment]
There's one mention of internal in the Active Directory section of the diagram.

It looks like there's also a subnet for the internal app ("delta_internal"), that can go as well. Though maybe a separate PR as it needs to be after the Delta repo Terraform changes.

**Comment by keithkennedy** [comment]
Thanks Ben,

Is terraform/production/ecr.tf the subnet you refer to? If so, I can undo this change.

**Comment by BenRamchandani** [comment]
We should get rid of the ECR repo too :+1:, but I meant in subnet.tf

**Comment by hugh-emerson** [comment]
Sorry unrelated change - I've spotted Grafana in the top right of the diagram which we do not use. Can you delete that?

**Comment by keithkennedy** [comment]
> Sorry unrelated change - I've spotted Grafana in the top right of the diagram which we do not use. Can you delete that?

Removed now

**Review by BenRamchandani — APPROVED** [review]

**Pull request merged**
